version: '3'

services:
    database:
        image: mysql:latest
        ports:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mypass
            MYSQL_DATABASE: db_carturesti
            MYSQL_USER: student
            MYSQL_PASSWORD: student
        volumes:
            - ./database:/docker-entrypoint-initdb.d/:ro
        security_opt:
            - seccomp:unconfined
    server:
        build: ./Server
        links:
            - database
        ports:
            - 5000:5000
    client:
        build: ./Client
        links:
            - database
        ports:
            - 5050:5050
