version: '3'

services:
    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_carturesti
            MYSQL_USER: student
            MYSQL_PASSWORD: student
        volumes:
            - ./database:/docker-entrypoint-initdb.d/:ro
        security_opt:
            - seccomp:unconfined
    server:
        # build: ./Server
        image: allexac/carturestionline:latest
        links:
            - database
        ports:
            - 5050:5050
    client:
        # build: ./Client
        image: allexac/carturestionline:client
        links:
            - database
        ports:
            - 5000:5000
